/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import type { IOperationResult } from '@microsoft/power-apps/data';
import type { Product } from '../models/OpenFoodFactsModel';
import { dataSourcesInfo } from '../../../.power/schemas/appschemas/dataSourcesInfo';
import { getClient } from '@microsoft/power-apps/data';


export class OpenFoodFactsService {
  private static readonly dataSourceName = 'OpenFoodFacts';

  private static readonly client = getClient(dataSourcesInfo);

  public static async GetProductByBarcode(barcode: string): Promise<IOperationResult<Product>> {
    const result = await OpenFoodFactsService.client.executeAsync<{ barcode: string }, Product>({
      connectorOperation: {
        tableName: OpenFoodFactsService.dataSourceName,
        operationName: 'GetProductByBarcode',
        parameters: { barcode },
      },
    });
    return result;
  }
}
